### ISSUE TITLE
Assignment 6-3 - Blog Tags

### ISSUE THREAD

**Issue by ambethia** [amie-wilt/assignments#29]
# Week 6 - Day 2

We're going to continue making a blog app.
- [x] Create a `Tag` model, it will probably have a `name`.
- [x] Create a `Tagging` model, it will have post and tag references.
- [x] Setup the many-to-many relationship between `Post` and `Tag`
- [x] The user should be able to add tags to a post when editing it (can be done a few ways, google will help you here, see how others solve this very same common problem)
- [x] The visitor facing post page should show a list of tags that a post was tagged with.
- [ ] _Bonus_: Make the listed tags from the previous feature link to a list of blog posts that have that tag.

**Comment by amie-wilt** [comment]
@ambethia:  Woo!! I actually got this one figured out pretty easily!! Definitely a record time on any homework assignment. Gonna give the Bonus a shot!

https://github.com/amie-wilt/blog-rails

**Comment by amie-wilt** [comment]
and heroku:

https://ancient-plains-3174.herokuapp.com

**Comment by ambethia** [comment]
![Awesome Work!](http://s3.amazonaws.com/giphygifs/media/ytwDCEeB9SWkDmMZBm/200w_d.gif)
