### ISSUE TITLE
Assignment 6-4 - Reddit Clone

### ISSUE THREAD

**Issue by ambethia** [amie-wilt/assignments#30]
# Week 6 - Day 4
## Description

Build a [Reddit](http://reddit.com) clone (bookmarks and voting in Rails using Forms and relationships). You'll be working in pairs on this. Pick one person to host the repo on Github, and add the other person as contributor so they have a 'commit bit'.
### Deliverables

Each of you should leave a comment for me on this issue with:
- \- [x] A github repo with your rails app
- \- [ ] A link to a live Heroku instance
### Requirements
- \- [x] Users can sign up/recover passwords/etc. (_hint:_ use [Devise](https://github.com/plataformatec/devise))
- \- [x] Links belong to the user who submitted them.
- \- [x] Each link should have many votes associated with it.
- \- [x] Clicking on up-vote for link should contribute to a positive score.
- \- [x] The front page should order by the score of an item (sum of it's votes).
- \- [x] links on the homepage should be paginated. (_hint:_ use [Kaminari](https://github.com/amatsuda/kaminari))
- \- [x] Other users should be able to comment on links. Comments do not need to be nested (that's a bonus item).
- \- [x] Make it look nice, Bootstrap, hand-rolled, etc.
- \- [x] Visitors can browse links and see comments, but they cannot create anything.
- \- [x] Fill your database in production (on Heroku) with many content. Consider working with the whole class to ask your peers to submit links and comment on each others apps. This will also help you find and discover bugs.
#### Bonuses
- \- [ ] Add some error tracking (e.g. Rollbar or HoneyBadger) and/or performance monitoring (e.g. New Relic)
- \- [x] Down-votes to reduce the score of an item
- \- [ ] Nest/thread comments like on Reddit.
- \- [ ] Up/down-vote for comments.
- \- [ ] Categories (sub-reddits), the front page should still show everything.
## Additional Resources
- Read [Active Record Associations](http://guides.rubyonrails.org/association_basics.html)
- Read [Rails Routing from the Outside In](http://guides.rubyonrails.org/routing.html)
- Read [Action Controller Overview](http://guides.rubyonrails.org/action_controller_overview.html)

**Comment by amie-wilt** [comment]
@ambethia:  here you go!

https://github.com/amie-wilt/reddit

https://enigmatic-stream-1494.herokuapp.com/

**Comment by ambethia** [comment]
![Awesome Work!](http://s3.amazonaws.com/giphygifs/media/eWdHhyOkIn0kw/200w_d.gif)
